/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    posts: Post;
    categories: Category;
    products: Product;
    orders: Order;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'store-settings': StoreSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        variant?:
          | (
              | 'highImpact'
              | 'mediumImpact'
              | 'lowImpact'
              | 'editorialAsymmetric'
              | 'bentoSplit'
              | 'gradientMeshSpotlight'
              | 'bentoCanvas'
              | 'agentInteractive'
              | 'spotlightStage'
              | 'textRevealCanvas'
              | 'cinemaImmersive'
              | 'bookSearch'
              | 'authorityPortrait'
              | 'statsLed'
              | 'founderLetter'
              | 'emailCapture'
              | 'codePreview'
              | 'productShowcase'
              | 'featuredQuote'
            )
          | null;
        /**
         * Small label above the heading (optional)
         */
        badge?: string | null;
        heading: string;
        subheading?: string | null;
        backgroundImage?: (number | null) | Media;
        /**
         * Direct MP4 URL (e.g. from Pexels Videos). Takes priority over backgroundImage on cinemaImmersive.
         */
        backgroundVideoUrl?: string | null;
        /**
         * Optional poster image URL shown while video loads
         */
        backgroundVideoPosterUrl?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        /**
         * Optional second CTA, e.g. "Book a Demo" alongside "Start Free"
         */
        secondaryCtaLabel?: string | null;
        secondaryCtaLink?: string | null;
        /**
         * Quantified trust signals shown inline (e.g. "10K+ teams", "Series B")
         */
        trustPills?:
          | {
              /**
               * e.g. "10K+", "$30M", "SOC 2"
               */
              value?: string | null;
              /**
               * e.g. "teams", "ARR", "compliant"
               */
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Customer/partner names for marquee under hero (e.g. "Linear", "Vercel")
         */
        proofLogoNames?:
          | {
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Small chips/tags shown below the CTA
         */
        highlights?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richContent';
      }
    | {
        heading: string;
        body?: string | null;
        linkLabel: string;
        linkUrl: string;
        variant?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        /**
         * Small label above heading
         */
        eyebrow?: string | null;
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        imagePosition?: ('left' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'brandNarrative';
      }
    | {
        variant?: ('default' | 'bentoAsymmetric' | 'numberedRail' | 'glassmorphicCards' | 'outcomeCards') | null;
        heading: string;
        subheading?: string | null;
        columns?: ('3' | '4') | null;
        features?:
          | {
              icon?:
                | ('star' | 'shield' | 'zap' | 'heart' | 'target' | 'users' | 'globe' | 'sparkles' | 'leaf' | 'clock')
                | null;
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGrid';
      }
    | {
        variant?: ('carousel' | 'marqueeWall') | null;
        heading: string;
        testimonials?:
          | {
              quote: string;
              author: string;
              role?: string | null;
              avatar?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        media: number | Media;
        caption?: string | null;
        size?: ('full' | 'contained') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        content: string;
        style?: ('info' | 'success' | 'warning') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        linkLabel?: string | null;
        linkUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'closingBanner';
      }
    | {
        form?: (number | null) | Form;
        heading?: string | null;
        subheading?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'formBlock';
      }
    | {
        variant?: ('rowOfNumbers' | 'tiledCards' | 'accentBand' | 'animatedCounter') | null;
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        stats?:
          | {
              /**
               * The number itself, e.g. 10,000 or 99.9
               */
              value: string;
              /**
               * Optional, e.g. $
               */
              prefix?: string | null;
              /**
               * Optional, e.g. + or % or K
               */
              suffix?: string | null;
              /**
               * What the number describes
               */
              label: string;
              /**
               * Optional citation
               */
              source?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        variant?: ('accordion' | 'twoColumn' | 'editorial') | null;
        eyebrow?: string | null;
        heading: string;
        subheading?: string | null;
        questions?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        variant?: ('row' | 'grid' | 'marquee') | null;
        /**
         * e.g. "Trusted by leading teams"
         */
        eyebrow?: string | null;
        heading?: string | null;
        logos?:
          | {
              /**
               * Customer / brand name
               */
              name: string;
              logo?: (number | null) | Media;
              /**
               * Optional link
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoCloud';
      }
    | {
        variant?: ('threeTier' | 'twoTier' | 'singleCard') | null;
        eyebrow?: string | null;
        heading: string;
        subheading?: string | null;
        tiers?:
          | {
              /**
               * e.g. Starter, Pro, Enterprise
               */
              name: string;
              /**
               * Display string, e.g. "$29" or "Free" or "Custom"
               */
              priceLabel: string;
              /**
               * e.g. /month, /seat, billed annually
               */
              billingCycle?: string | null;
              /**
               * One-line description of who it's for
               */
              description?: string | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel: string;
              ctaLink: string;
              /**
               * Visually emphasize as recommended
               */
              highlighted?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        variant?: ('numberedRow' | 'verticalTimeline' | 'iconRow') | null;
        eyebrow?: string | null;
        heading: string;
        subheading?: string | null;
        steps?:
          | {
              title: string;
              description: string;
              icon?:
                | ('sparkles' | 'compass' | 'settings' | 'rocket' | 'check' | 'target' | 'lightbulb' | 'handshake')
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'process';
      }
    | {
        variant?: ('editorial' | 'brandStatement' | 'spotlight') | null;
        /**
         * The pull-out statement (no need for surrounding quotes)
         */
        quote: string;
        /**
         * Person's name (optional)
         */
        attribution?: string | null;
        /**
         * Role / company (optional)
         */
        attributionRole?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pullQuote';
      }
    | {
        variant?: ('weekGrid' | 'stackedList' | 'inlineBanner') | null;
        /**
         * e.g. "Visit us"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Exactly 7 entries — one per day, Monday first.
         */
        days?:
          | {
              day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
              /**
               * e.g. "07:00" — leave blank if closed
               */
              openTime?: string | null;
              /**
               * e.g. "21:00" — leave blank if closed
               */
              closeTime?: string | null;
              /**
               * Optional, e.g. "Kitchen closes at 21:30"
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * e.g. "America/New_York" — used to compute Open Now badge.
         */
        timezone?: string | null;
        /**
         * Optional CTA below the schedule, e.g. "Reserve a table"
         */
        ctaLabel?: string | null;
        ctaLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openingHoursWidget';
      }
    | {
        variant?: ('list' | 'badgesGrid' | 'featuredPlus') | null;
        /**
         * e.g. "Upcoming"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        events?:
          | {
              title: string;
              /**
               * ISO-8601 date or human, e.g. "2026-06-15"
               */
              startDate: string;
              /**
               * Optional end date for multi-day events.
               */
              endDate?: string | null;
              /**
               * e.g. "7:00 PM"
               */
              time?: string | null;
              /**
               * Venue or "Online"
               */
              location?: string | null;
              description?: string | null;
              /**
               * CTA label, e.g. "RSVP" or "Learn more"
               */
              rsvpLabel?: string | null;
              rsvpLink?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Link below the list, e.g. "See full calendar"
         */
        allEventsLabel?: string | null;
        allEventsLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'eventCalendarTeaser';
      }
    | {
        variant?: ('twoColumn' | 'categorizedCards' | 'tastingMenu') | null;
        eyebrow?: string | null;
        heading?: string | null;
        /**
         * Sets the tone — e.g. "A sample from this season"
         */
        subheading?: string | null;
        /**
         * Group items by section (e.g. Starters, Mains, Wine).
         */
        categories?:
          | {
              /**
               * Section name, e.g. "Starters"
               */
              name: string;
              items?:
                | {
                    name: string;
                    description?: string | null;
                    /**
                     * Display price, e.g. "$24" or "$$"
                     */
                    price?: string | null;
                    /**
                     * Comma-sep, e.g. "v, gf, contains nuts"
                     */
                    tags?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * CTA below preview, e.g. "See full menu"
         */
        fullMenuLabel?: string | null;
        fullMenuLink?: string | null;
        /**
         * Optional direct link to a PDF.
         */
        menuPdfUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuPreview';
      }
    | {
        variant?: ('inline' | 'splitWithImage' | 'fullBand') | null;
        /**
         * e.g. "Book your stay"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Acceptable party sizes (e.g. 2-12).
         */
        partySizeOptions?:
          | {
              value: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Hospitality only — minimum nights per booking.
         */
        minNights?: number | null;
        /**
         * Hospitality only — maximum nights.
         */
        maxNights?: number | null;
        /**
         * Capture email at submission time (recommended).
         */
        requireGuestEmail?: boolean | null;
        ctaLabel?: string | null;
        /**
         * Where to send the user on submit — own booking engine, OpenTable, Resy, Tock, etc.
         */
        destinationUrl?: string | null;
        /**
         * Used by the splitWithImage variant.
         */
        sideImage?: (number | null) | Media;
        /**
         * Optional small print, e.g. "Reservations open 90 days out."
         */
        disclaimer?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'reservationWidget';
      }
    | {
        variant?: ('splitCard' | 'stackedCard' | 'fullBanner') | null;
        /**
         * e.g. "Find us"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * One entry per physical location.
         */
        locations?:
          | {
              /**
               * e.g. "Main Showroom" or city name
               */
              name: string;
              addressLine1: string;
              addressLine2?: string | null;
              city?: string | null;
              /**
               * State / province
               */
              region?: string | null;
              postcode?: string | null;
              country?: string | null;
              phone?: string | null;
              email?: string | null;
              /**
               * Google Maps / Mapbox iframe src URL. Leave blank for a placeholder.
               */
              mapEmbedUrl?: string | null;
              /**
               * Deep link to maps app for directions.
               */
              directionsUrl?: string | null;
              /**
               * e.g. "5 min walk from Union Square station"
               */
              transitNote?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'locationMap';
      }
    | {
        variant?: ('sliderStack' | 'questionSteps' | 'cardPicker') | null;
        /**
         * e.g. "Pricing estimate"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Variables the user adjusts.
         */
        inputs?:
          | {
              type: 'slider' | 'select' | 'toggle';
              label: string;
              /**
               * e.g. "hours", "team members", "%"
               */
              unit?: string | null;
              min?: number | null;
              max?: number | null;
              step?: number | null;
              default?: number | null;
              /**
               * For select / toggle inputs.
               */
              options?:
                | {
                    label: string;
                    /**
                     * Multiplier applied to the base rate when this option is picked.
                     */
                    multiplier?: number | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Base dollar amount to anchor the estimate.
         */
        baseRate?: number | null;
        /**
         * e.g. "$", "£"
         */
        currencyPrefix?: string | null;
        /**
         * e.g. "/mo", " USD"
         */
        currencySuffix?: string | null;
        /**
         * Round estimate to nearest N (e.g. 100 => $1,200 not $1,247).
         */
        roundTo?: number | null;
        /**
         * e.g. "This is an estimate. Final scope confirmed after a 30-min call."
         */
        disclaimer?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceCalculator';
      }
    | {
        variant?: ('verticalSpine' | 'horizontalScroll' | 'decadeBands') | null;
        /**
         * e.g. "Since 1962"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Chronological — earliest first. Layout sorts client-side as a fallback.
         */
        milestones?:
          | {
              /**
               * e.g. "1962" or "Spring 2020"
               */
              year: string;
              title: string;
              description?: string | null;
              /**
               * Optional — archival photo, product shot, etc.
               */
              image?: (number | null) | Media;
              /**
               * Visually emphasize this milestone.
               */
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional closing statement, e.g. "And we are just getting started."
         */
        closingLine?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'brandTimeline';
      }
    | {
        variant?: ('grid' | 'list' | 'featured') | null;
        /**
         * e.g. "Latest stories"
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Max number of posts to show.
         */
        limit?: number | null;
        /**
         * Optional — filter by a single category.
         */
        category?: (number | null) | Category;
        showImage?: boolean | null;
        /**
         * Show a short excerpt under each post title.
         */
        showExcerpt?: boolean | null;
        ctaLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'postsList';
      }
    | {
        variant?: ('grid' | 'featured' | 'minimal') | null;
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        /**
         * Only show products in this category (leave empty for all)
         */
        category?: string | null;
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productGrid';
      }
    | {
        /**
         * Exported .splinecode URL (Spline → Export → Code). Must be a scene you are licensed to use commercially.
         */
        sceneUrl: string;
        variant?: ('heroOverlay' | 'split' | 'showcase') | null;
        /**
         * Optional. Shown for heroOverlay / split variants.
         */
        heading?: string | null;
        subheading?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        height?: ('compact' | 'tall' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'splineScene';
      }
    | {
        /**
         * Optional label for this creator section (editor only).
         */
        name?: string | null;
        /**
         * Declarative node tree: { "nodes": [...] }. Rendered by the sandboxed renderer.
         */
        spec:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'creatorBlock';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Your sellable catalog. Each product gets its own page at /products/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  /**
   * Price in your store currency (e.g. 48 or 48.50)
   */
  price: number;
  /**
   * Optional “was” price shown struck through
   */
  compareAtPrice?: number | null;
  /**
   * 1-2 sentences shown on product cards and below the title
   */
  shortDescription?: string | null;
  /**
   * Full description — materials, process, what makes it special
   */
  description?: string | null;
  /**
   * Primary product image (preferred over Image URL when both set)
   */
  image?: (number | null) | Media;
  /**
   * Fallback image URL used when no Media upload is set
   */
  imageUrl?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        imageUrl?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-form grouping, e.g. "Candles"
   */
  category?: string | null;
  /**
   * Optional card badge, e.g. "Best Seller"
   */
  badge?: string | null;
  /**
   * Spec rows — Materials, Dimensions, Care…
   */
  details?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to hide the buy button (still browsable)
   */
  available?: boolean | null;
  trackInventory?: boolean | null;
  /**
   * Units on hand — only enforced when Track Inventory is on
   */
  stock?: number | null;
  /**
   * Per-product shipping/lead-time note, e.g. "Ships in 2-3 days"
   */
  shippingNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Orders land here automatically when Stripe checkout completes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  items: {
    product?: (number | null) | Product;
    name: string;
    unitPrice: number;
    quantity: number;
    id?: string | null;
  }[];
  subtotal: number;
  shippingTotal?: number | null;
  total: number;
  currency: string;
  customerEmail?: string | null;
  customerName?: string | null;
  shippingAddress?: string | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  /**
   * Internal fulfillment notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  products?: {
    /**
     * Allow clients to find products.
     */
    find?: boolean | null;
    /**
     * Allow clients to create products.
     */
    create?: boolean | null;
    /**
     * Allow clients to update products.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete products.
     */
    delete?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update header global.
     */
    update?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update footer global.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              badge?: T;
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              backgroundVideoUrl?: T;
              backgroundVideoPosterUrl?: T;
              ctaLabel?: T;
              ctaLink?: T;
              secondaryCtaLabel?: T;
              secondaryCtaLink?: T;
              trustPills?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              proofLogoNames?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              linkLabel?: T;
              linkUrl?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        brandNarrative?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              variant?: T;
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              content?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        closingBanner?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              linkLabel?: T;
              linkUrl?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              form?: T;
              heading?: T;
              subheading?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    prefix?: T;
                    suffix?: T;
                    label?: T;
                    source?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              logos?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    priceLabel?: T;
                    billingCycle?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaLink?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              variant?: T;
              quote?: T;
              attribution?: T;
              attributionRole?: T;
              id?: T;
              blockName?: T;
            };
        openingHoursWidget?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              days?:
                | T
                | {
                    day?: T;
                    openTime?: T;
                    closeTime?: T;
                    note?: T;
                    id?: T;
                  };
              timezone?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        eventCalendarTeaser?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              events?:
                | T
                | {
                    title?: T;
                    startDate?: T;
                    endDate?: T;
                    time?: T;
                    location?: T;
                    description?: T;
                    rsvpLabel?: T;
                    rsvpLink?: T;
                    image?: T;
                    id?: T;
                  };
              allEventsLabel?: T;
              allEventsLink?: T;
              id?: T;
              blockName?: T;
            };
        menuPreview?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              categories?:
                | T
                | {
                    name?: T;
                    items?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          price?: T;
                          tags?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              fullMenuLabel?: T;
              fullMenuLink?: T;
              menuPdfUrl?: T;
              id?: T;
              blockName?: T;
            };
        reservationWidget?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              partySizeOptions?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              minNights?: T;
              maxNights?: T;
              requireGuestEmail?: T;
              ctaLabel?: T;
              destinationUrl?: T;
              sideImage?: T;
              disclaimer?: T;
              id?: T;
              blockName?: T;
            };
        locationMap?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              locations?:
                | T
                | {
                    name?: T;
                    addressLine1?: T;
                    addressLine2?: T;
                    city?: T;
                    region?: T;
                    postcode?: T;
                    country?: T;
                    phone?: T;
                    email?: T;
                    mapEmbedUrl?: T;
                    directionsUrl?: T;
                    transitNote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceCalculator?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              inputs?:
                | T
                | {
                    type?: T;
                    label?: T;
                    unit?: T;
                    min?: T;
                    max?: T;
                    step?: T;
                    default?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          multiplier?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              baseRate?: T;
              currencyPrefix?: T;
              currencySuffix?: T;
              roundTo?: T;
              disclaimer?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        brandTimeline?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    highlight?: T;
                    id?: T;
                  };
              closingLine?: T;
              id?: T;
              blockName?: T;
            };
        postsList?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              limit?: T;
              category?: T;
              showImage?: T;
              showExcerpt?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              category?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        splineScene?:
          | T
          | {
              sceneUrl?: T;
              variant?: T;
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaLink?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        creatorBlock?:
          | T
          | {
              name?: T;
              spec?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  compareAtPrice?: T;
  shortDescription?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        alt?: T;
        id?: T;
      };
  category?: T;
  badge?: T;
  details?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  available?: T;
  trackInventory?: T;
  stock?: T;
  shippingNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        name?: T;
        unitPrice?: T;
        quantity?: T;
        id?: T;
      };
  subtotal?: T;
  shippingTotal?: T;
  total?: T;
  currency?: T;
  customerEmail?: T;
  customerName?: T;
  shippingAddress?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  products?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  header?:
    | T
    | {
        find?: T;
        update?: T;
      };
  footer?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Text logo / brand name
   */
  brandLabel?: string | null;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional CTA button in header
   */
  ctaButton?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short about text in footer
   */
  description?: string | null;
  /**
   * Name used in copyright line
   */
  copyrightName?: string | null;
  /**
   * Primary phone number for the business
   */
  phone?: string | null;
  /**
   * Street address or service area
   */
  address?: string | null;
  /**
   * Opening hours shown in the footer
   */
  businessHours?: string | null;
  /**
   * Google Maps or Apple Maps URL
   */
  mapLink?: string | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'instagram' | 'linkedin' | 'facebook' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  bottomMessage?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  favicon?: (number | null) | Media;
  /**
   * Social sharing image used for Open Graph and Twitter cards
   */
  ogImage?: (number | null) | Media;
  theme?: {
    palette?:
      | (
          | 'midnight'
          | 'ocean'
          | 'forest'
          | 'sunset'
          | 'lavender'
          | 'ember'
          | 'charcoal'
          | 'cream'
          | 'sage'
          | 'cobalt'
          | 'terracotta'
          | 'slate'
          | 'noir'
          | 'bloom'
        )
      | null;
    fontPairing?:
      | (
          | 'geist-inter'
          | 'playfair-inter'
          | 'playfair-sourcesans'
          | 'dmsans-dmserif'
          | 'spacegrotesk-inter'
          | 'fraunces-inter'
          | 'instrumentserif-inter'
          | 'archivo-archivo'
          | 'cormorant-jost'
        )
      | null;
    borderRadius?: ('none' | 'sm' | 'md' | 'lg') | null;
    /**
     * Per-tenant synthesized palette (10 hex codes). When present, overrides the palette slug.
     */
    customColors?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Per-tenant synthesized heading font (Google Fonts family name, e.g. "Cormorant Garamond")
     */
    customFontHeading?: string | null;
    /**
     * Per-tenant synthesized body font (Google Fonts family name)
     */
    customFontBody?: string | null;
    /**
     * Pre-built Google Fonts URL for the custom heading + body pair
     */
    customGoogleFontsUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Connect your own Stripe account to start selling. Your keys never leave this site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  /**
   * Master switch — shows the cart and buy buttons across the site
   */
  storeEnabled?: boolean | null;
  currency?: ('usd' | 'eur' | 'gbp' | 'cad' | 'aud' | 'inr') | null;
  /**
   * From dashboard.stripe.com → Developers → API keys
   */
  stripe?: {
    /**
     * pk_live_… or pk_test_…
     */
    publishableKey?: string | null;
    /**
     * sk_live_… or sk_test_… — never exposed publicly
     */
    secretKey?: string | null;
    /**
     * whsec_… — add a webhook endpoint for {your-domain}/api/stripe-webhook with event checkout.session.completed
     */
    webhookSecret?: string | null;
  };
  shipping?: {
    /**
     * Flat shipping per order in store currency. 0 = free shipping.
     */
    flatRate?: number | null;
    /**
     * Orders at or above this subtotal ship free (leave empty to disable)
     */
    freeShippingThreshold?: number | null;
    /**
     * Shown on product pages — e.g. "Ships worldwide in 2-5 business days"
     */
    shippingPolicy?: string | null;
  };
  /**
   * Shown on product pages — the single cheapest trust signal you can write
   */
  returnsPolicy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brandLabel?: T;
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  copyrightName?: T;
  phone?: T;
  address?: T;
  businessHours?: T;
  mapLink?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  bottomMessage?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  favicon?: T;
  ogImage?: T;
  theme?:
    | T
    | {
        palette?: T;
        fontPairing?: T;
        borderRadius?: T;
        customColors?: T;
        customFontHeading?: T;
        customFontBody?: T;
        customGoogleFontsUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  storeEnabled?: T;
  currency?: T;
  stripe?:
    | T
    | {
        publishableKey?: T;
        secretKey?: T;
        webhookSecret?: T;
      };
  shipping?:
    | T
    | {
        flatRate?: T;
        freeShippingThreshold?: T;
        shippingPolicy?: T;
      };
  returnsPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}